// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAddress = "address"

// Address mapped from table <address>
type Address struct {
	ID      int64  `gorm:"column:id;type:bigint;not null;comment:邮箱地址主键" json:"id"`                     // 邮箱地址主键
	Email   string `gorm:"column:email;type:character varying(254);not null;comment:邮箱地址" json:"email"` // 邮箱地址
	UserID  int64  `gorm:"column:user_id;type:bigint;not null;comment:用户id" json:"user_id"`             // 用户id
	Primary int16  `gorm:"column:primary;type:smallint;not null;comment:是否主要邮箱地址" json:"primary"`       // 是否主要邮箱地址
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
