// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBlock = "block"

// Block mapped from table <block>
type Block struct {
	ID          *int64     `gorm:"column:id;type:bigint;comment:用户模块id" json:"id"`                                       // 用户模块id
	Name        *string    `gorm:"column:name;type:character varying(36);comment:模块名称" json:"name"`                      // 模块名称
	Description *string    `gorm:"column:description;type:character varying(255);comment:描述" json:"description"`         // 描述
	Createtime  *time.Time `gorm:"column:createtime;type:timestamp(6) without time zone;comment:创建时间" json:"createtime"` // 创建时间
	Updatetime  *time.Time `gorm:"column:updatetime;type:timestamp(6) without time zone;comment:修改时间" json:"updatetime"` // 修改时间
}

// TableName Block's table name
func (*Block) TableName() string {
	return TableNameBlock
}
