// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCarousel = "carousel"

// Carousel mapped from table <carousel>
type Carousel struct {
	ID          *int64     `gorm:"column:id;type:bigint;comment:主键id" json:"id"`                                         // 主键id
	Title       *string    `gorm:"column:title;type:character varying(100);comment:标题" json:"title"`                     // 标题
	Description *string    `gorm:"column:description;type:character varying(200);comment:描述" json:"description"`         // 描述
	FileID      *int64     `gorm:"column:file_id;type:bigint;comment:文件id" json:"file_id"`                               // 文件id
	VideoID     *int64     `gorm:"column:video_id;type:bigint;comment:视频id" json:"video_id"`                             // 视频id
	CreateTime  *time.Time `gorm:"column:createTime;type:timestamp(0) without time zone;comment:创建时间" json:"createTime"` // 创建时间
	UpdateTime  *time.Time `gorm:"column:updateTime;type:timestamp(0) without time zone;comment:更新时间" json:"updateTime"` // 更新时间
}

// TableName Carousel's table name
func (*Carousel) TableName() string {
	return TableNameCarousel
}
