// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	ID             int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:分类id" json:"id"`                      // 分类id
	Identification string     `gorm:"column:identification;type:uuid;not null;comment:唯一标识每个分类条目" json:"identification"`               // 唯一标识每个分类条目
	CreateTime     time.Time  `gorm:"column:create_time;type:timestamp(6) without time zone;not null;comment:添加时间" json:"create_time"` // 添加时间
	Name           string     `gorm:"column:name;type:character varying(100);not null;comment:分类名称" json:"name"`                       // 分类名称
	Description    string     `gorm:"column:description;type:text;not null;comment:分类描述" json:"description"`                           // 分类描述
	MediaCount     int32      `gorm:"column:media_count;type:integer;not null;comment:媒体数量" json:"media_count"`                        // 媒体数量
	Thumbnail      string     `gorm:"column:thumbnail;type:character varying(100);not null;comment:分类的缩略图" json:"thumbnail"`           // 分类的缩略图
	UserID         *int64     `gorm:"column:user_id;type:bigint;comment:用户id" json:"user_id"`                                          // 用户id
	UpdateTime     *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"`                          // 更新时间
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
