// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChannel = "channel"

// Channel mapped from table <channel>
type Channel struct {
	ID          int32      `gorm:"column:id;type:integer;not null;comment:用户频道信息id" json:"id"`                                               // 用户频道信息id
	Title       string     `gorm:"column:title;type:character varying(90);not null;comment:用户频道信息标题" json:"title"`                           // 用户频道信息标题
	Description string     `gorm:"column:description;type:text;not null;comment:用户频道信息描述" json:"description"`                                // 用户频道信息描述
	CreateTime  time.Time  `gorm:"column:create_time;type:timestamp(6) with time zone;not null;comment:添加时间" json:"create_time"`             // 添加时间
	BannerLogo  string     `gorm:"column:banner_logo;type:character varying(100);not null;comment:频道的横幅或标志的路径，表示频道的品牌标识" json:"banner_logo"` // 频道的横幅或标志的路径，表示频道的品牌标识
	UserID      int32      `gorm:"column:user_id;type:integer;not null;comment:用户id" json:"user_id"`                                         // 用户id
	UpdateTime  *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"`                                   // 更新时间
}

// TableName Channel's table name
func (*Channel) TableName() string {
	return TableNameChannel
}
