// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChannelSubscriber = "channel_subscribers"

// ChannelSubscriber mapped from table <channel_subscribers>
type ChannelSubscriber struct {
	ID        int64 `gorm:"column:id;type:bigint;not null;comment:用户频道的订阅者信息id" json:"id"`         // 用户频道的订阅者信息id
	ChannelID int64 `gorm:"column:channel_id;type:bigint;not null;comment:频道id" json:"channel_id"` // 频道id
	UserID    int64 `gorm:"column:user_id;type:bigint;not null;comment:用户id" json:"user_id"`       // 用户id
}

// TableName ChannelSubscriber's table name
func (*ChannelSubscriber) TableName() string {
	return TableNameChannelSubscriber
}
