// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChat = "chat"

// Chat mapped from table <chat>
type Chat struct {
	ID            *int64     `gorm:"column:id;type:bigint;comment:聊天id" json:"id"`                                           // 聊天id
	Content       *string    `gorm:"column:content;type:text;comment:内容" json:"content"`                                     // 内容
	SendUserID    *int64     `gorm:"column:send_user_id;type:bigint;comment:发送用户id" json:"send_user_id"`                     // 发送用户id
	IsOnline      *int16     `gorm:"column:is_online;type:smallint;comment:是否在线" json:"is_online"`                           // 是否在线
	ReceiveUserID *string    `gorm:"column:receive_user_id;type:character varying(50);comment:目标用户" json:"receive_user_id"`  // 目标用户
	CreateTime    *time.Time `gorm:"column:create_time;type:timestamp(6) without time zone;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime    *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"`                 // 更新时间
}

// TableName Chat's table name
func (*Chat) TableName() string {
	return TableNameChat
}
