// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChatQueue = "chat_queue"

// ChatQueue mapped from table <chat_queue>
type ChatQueue struct {
	ID            *int64     `gorm:"column:id;type:bigint;comment:主键id" json:"id"`                                           // 主键id
	Content       *string    `gorm:"column:content;type:text;comment:内容" json:"content"`                                     // 内容
	SendUserID    *int64     `gorm:"column:send_user_id;type:bigint;comment:发送者id" json:"send_user_id"`                      // 发送者id
	ReceiveUserID *int64     `gorm:"column:receive_user_id;type:bigint;comment:目标人id" json:"receive_user_id"`                // 目标人id
	CreateTime    *time.Time `gorm:"column:create_time;type:timestamp(0) without time zone;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime    *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"`                 // 更新时间
}

// TableName ChatQueue's table name
func (*ChatQueue) TableName() string {
	return TableNameChatQueue
}
