// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCollect = "collect"

// Collect mapped from table <collect>
type Collect struct {
	ID          *int64     `gorm:"column:id;type:bigint;comment:主键" json:"id"`                                             // 主键
	Name        *string    `gorm:"column:name;type:character varying(200);comment:名称" json:"name"`                         // 名称
	Cover       *string    `gorm:"column:cover;type:character varying(255);comment:封面" json:"cover"`                       // 封面
	Description *string    `gorm:"column:description;type:text;comment:描述" json:"description"`                             // 描述
	UserID      *int64     `gorm:"column:user_id;type:bigint;comment:用户id" json:"user_id"`                                 // 用户id
	CreateTime  *time.Time `gorm:"column:create_time;type:timestamp(6) without time zone;comment:开始时间" json:"create_time"` // 开始时间
	UpdateTime  *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"`                 // 更新时间
}

// TableName Collect's table name
func (*Collect) TableName() string {
	return TableNameCollect
}
