// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCollectVideo = "collect_video"

// CollectVideo mapped from table <collect_video>
type CollectVideo struct {
	CategoryID int64 `gorm:"column:category_id;type:bigint;not null;comment:分类id" json:"category_id"` // 分类id
	VideoID    int64 `gorm:"column:video_id;type:bigint;not null;comment:视频id" json:"video_id"`       // 视频id
	ItemSort   int32 `gorm:"column:item_sort;type:integer;not null;comment:排序" json:"item_sort"`      // 排序
	ID         int64 `gorm:"column:id;type:bigint;primaryKey;comment:主键id" json:"id"`                 // 主键id
}

// TableName CollectVideo's table name
func (*CollectVideo) TableName() string {
	return TableNameCollectVideo
}
