// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID         int64      `gorm:"column:id;type:bigint;primaryKey;comment:评论表id" json:"id"`                                     // 评论表id
	VideoID    float64    `gorm:"column:video_id;type:numeric(20,0);not null;comment:文章id" json:"video_id"`                     // 文章id
	Content    string     `gorm:"column:content;type:character varying(255);not null;comment:内容" json:"content"`                // 内容
	UserID     int64      `gorm:"column:user_id;type:bigint;not null;comment:回复用户id" json:"user_id"`                            // 回复用户id
	Nickname   string     `gorm:"column:nickname;type:character varying(36);not null;comment:回复用户昵称" json:"nickname"`           // 回复用户昵称
	Avatar     string     `gorm:"column:avatar;type:character varying(255);not null;comment:回复头像" json:"avatar"`                // 回复头像
	Status     int16      `gorm:"column:status;type:smallint;not null;comment:评价状态  0 待审核  1 已批准 2 垃圾 3 回收站" json:"status"`     // 评价状态  0 待审核  1 已批准 2 垃圾 3 回收站
	ReplyCount *int32     `gorm:"column:reply_count;type:integer;comment:回复次数" json:"reply_count"`                              // 回复次数
	CreateTime time.Time  `gorm:"column:create_time;type:timestamp without time zone;not null;comment:评论时间" json:"create_time"` // 评论时间
	UpdateTime *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"`                       // 修改时间
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
