// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDanmu = "danmu"

// Danmu mapped from table <danmu>
type Danmu struct {
	ID         *int64     `gorm:"column:id;type:bigint;comment:弹幕id" json:"id"`                                         // 弹幕id
	Text       *string    `gorm:"column:text;type:character varying(100);comment:弹幕内容" json:"text"`                     // 弹幕内容
	Time       *int32     `gorm:"column:time;type:integer;comment:时间" json:"time"`                                      // 时间
	VideoID    *int64     `gorm:"column:video_id;type:bigint;comment:视频id" json:"video_id"`                             // 视频id
	UserID     *int64     `gorm:"column:user_id;type:bigint;comment:用户id" json:"user_id"`                               // 用户id
	Createtime *time.Time `gorm:"column:createtime;type:timestamp(6) without time zone;comment:创建时间" json:"createtime"` // 创建时间
	Updatetime *time.Time `gorm:"column:updatetime;type:timestamp(6) without time zone;comment:更新时间" json:"updatetime"` // 更新时间
}

// TableName Danmu's table name
func (*Danmu) TableName() string {
	return TableNameDanmu
}
