// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMediaTag = "media_tags"

// MediaTag mapped from table <media_tags>
type MediaTag struct {
	ID      int64 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:媒体文件的标签信息中间表id" json:"id"` // 媒体文件的标签信息中间表id
	MediaID int64 `gorm:"column:media_id;type:bigint;not null;comment:媒体id" json:"media_id"`                    // 媒体id
	TagID   int64 `gorm:"column:tag_id;type:bigint;not null;comment:标签id" json:"tag_id"`                        // 标签id
}

// TableName MediaTag's table name
func (*MediaTag) TableName() string {
	return TableNameMediaTag
}
