// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMediaPlaylist = "media_playlist"

// MediaPlaylist mapped from table <media_playlist>
type MediaPlaylist struct {
	ID            int32     `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:播放列表id" json:"id"`                          // 播放列表id
	AddDate       time.Time `gorm:"column:add_date;type:timestamp(6) with time zone;not null;comment:添加时间" json:"add_date"`                 // 添加时间
	Description   string    `gorm:"column:description;type:text;not null;comment:描述信息" json:"description"`                                  // 描述信息
	FriendlyToken string    `gorm:"column:friendly_token;type:character varying(12);not null;comment:友好的令牌，可能用于公开访问" json:"friendly_token"` // 友好的令牌，可能用于公开访问
	Title         string    `gorm:"column:title;type:character varying(100);not null;comment:标题" json:"title"`                              // 标题
	UID           string    `gorm:"column:uid;type:uuid;not null;comment:播放列表的唯一标识符" json:"uid"`                                            // 播放列表的唯一标识符
	UserID        int32     `gorm:"column:user_id;type:integer;not null;comment:用户id" json:"user_id"`                                       // 用户id
}

// TableName MediaPlaylist's table name
func (*MediaPlaylist) TableName() string {
	return TableNameMediaPlaylist
}
