// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMediaPlaylistmedium = "media_playlistmedia"

// MediaPlaylistmedium mapped from table <media_playlistmedia>
type MediaPlaylistmedium struct {
	ID         int32     `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:播放列表中媒体文件的关联信息id" json:"id"`        // 播放列表中媒体文件的关联信息id
	ActionDate time.Time `gorm:"column:action_date;type:timestamp(6) with time zone;not null;comment:操作日期时间" json:"action_date"` // 操作日期时间
	Ordering   int32     `gorm:"column:ordering;type:integer;not null;comment:媒体在播放列表中的顺序" json:"ordering"`                      // 媒体在播放列表中的顺序
	MediaID    int32     `gorm:"column:media_id;type:integer;not null;comment:媒体id" json:"media_id"`                             // 媒体id
	PlaylistID int32     `gorm:"column:playlist_id;type:integer;not null;comment:播放列表id" json:"playlist_id"`                     // 播放列表id
}

// TableName MediaPlaylistmedium's table name
func (*MediaPlaylistmedium) TableName() string {
	return TableNameMediaPlaylistmedium
}
