// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMediaSubtitle = "media_subtitle"

// MediaSubtitle mapped from table <media_subtitle>
type MediaSubtitle struct {
	ID           int32  `gorm:"column:id;type:integer;not null;comment:媒体文件的字幕信息id" json:"id"`                                       // 媒体文件的字幕信息id
	SubtitleFile string `gorm:"column:subtitle_file;type:character varying(500);not null;comment:字幕文件的路径或 URL" json:"subtitle_file"` // 字幕文件的路径或 URL
	LanguageID   int32  `gorm:"column:language_id;type:integer;not null;comment:字幕语言id" json:"language_id"`                          // 字幕语言id
	MediaID      int32  `gorm:"column:media_id;type:integer;not null;comment:媒体id" json:"media_id"`                                  // 媒体id
	UserID       int32  `gorm:"column:user_id;type:integer;not null;comment:用户id" json:"user_id"`                                    // 用户id
}

// TableName MediaSubtitle's table name
func (*MediaSubtitle) TableName() string {
	return TableNameMediaSubtitle
}
