// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMediaLater = "media_later"

// MediaLater mapped from table <media_later>
type MediaLater struct {
	ID         int64      `gorm:"column:id;type:bigint;primaryKey;comment:主键id" json:"id"`                                // 主键id
	MediaID    int64      `gorm:"column:media_id;type:bigint;not null;comment:视频id" json:"media_id"`                      // 视频id
	UserID     int64      `gorm:"column:user_id;type:bigint;not null;comment:用户id" json:"user_id"`                        // 用户id
	CreateTime *time.Time `gorm:"column:create_time;type:timestamp(6) without time zone;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"`                 // 更新时间
}

// TableName MediaLater's table name
func (*MediaLater) TableName() string {
	return TableNameMediaLater
}
