// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMoment = "moment"

// Moment mapped from table <moment>
type Moment struct {
	ID         *string    `gorm:"column:id;type:character varying(50)" json:"id"`
	Title      *string    `gorm:"column:title;type:character varying(255);comment:标题" json:"title"`                     // 标题
	Content    *string    `gorm:"column:content;type:text;comment:内容" json:"content"`                                   // 内容
	Vid        *string    `gorm:"column:vid;type:character varying(50);comment:关联视频" json:"vid"`                        // 关联视频
	Userid     *string    `gorm:"column:userid;type:character varying(50);comment:创建人" json:"userid"`                   // 创建人
	Cid        *string    `gorm:"column:cid;type:character varying(50);comment:频道" json:"cid"`                          // 频道
	Createtime *time.Time `gorm:"column:createtime;type:timestamp(6) without time zone;comment:创建时间" json:"createtime"` // 创建时间
	Updatetime *time.Time `gorm:"column:updatetime;type:timestamp(6) without time zone;comment:更新时间" json:"updatetime"` // 更新时间
}

// TableName Moment's table name
func (*Moment) TableName() string {
	return TableNameMoment
}
