// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNotification = "notification"

// Notification mapped from table <notification>
type Notification struct {
	ID     int64  `gorm:"column:id;type:bigint;not null;comment:用户通知id" json:"id"`                                                // 用户通知id
	Action string `gorm:"column:action;type:character varying(30);not null;comment:通知涉及的动作" json:"action"`                        // 通知涉及的动作
	Method string `gorm:"column:method;type:character varying(20);not null;comment:发送通知的方法，例如 "邮件"、"短信"、"应用内通知" 等" json:"method"` // 发送通知的方法，例如 "邮件"、"短信"、"应用内通知" 等
	UserID int64  `gorm:"column:user_id;type:bigint;not null;comment:用户id" json:"user_id"`                                        // 用户id
	Notify int16  `gorm:"column:notify;type:smallint;not null;comment:是否发送通知" json:"notify"`                                      // 是否发送通知
}

// TableName Notification's table name
func (*Notification) TableName() string {
	return TableNameNotification
}
