// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRating = "rating"

// Rating mapped from table <rating>
type Rating struct {
	ID               int32     `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:用户对媒体文件的评分信息id" json:"id"`    // 用户对媒体文件的评分信息id
	AddDate          time.Time `gorm:"column:add_date;type:timestamp(6) with time zone;not null;comment:添加时间" json:"add_date"`   // 添加时间
	Score            int32     `gorm:"column:score;type:integer;not null;comment:评分" json:"score"`                               // 评分
	MediaID          int32     `gorm:"column:media_id;type:integer;not null;comment:媒体id" json:"media_id"`                       // 媒体id
	RatingCategoryID int32     `gorm:"column:rating_category_id;type:integer;not null;comment:评分分类id" json:"rating_category_id"` // 评分分类id
	UserID           int32     `gorm:"column:user_id;type:integer;not null;comment:用户id" json:"user_id"`                         // 用户id
}

// TableName Rating's table name
func (*Rating) TableName() string {
	return TableNameRating
}
