// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReply = "reply"

// Reply mapped from table <reply>
type Reply struct {
	ID           int64      `gorm:"column:id;type:bigint;primaryKey;comment:回复表id" json:"id"`                                     // 回复表id
	CommentID    int64      `gorm:"column:comment_id;type:bigint;not null;comment:评论表id" json:"comment_id"`                       // 评论表id
	Pid          int64      `gorm:"column:pid;type:bigint;not null;comment:回复父id" json:"pid"`                                     // 回复父id
	Content      string     `gorm:"column:content;type:character varying(255);not null;comment:内容" json:"content"`                // 内容
	FromUserID   int64      `gorm:"column:from_user_id;type:bigint;not null;comment:回复用户id" json:"from_user_id"`                  // 回复用户id
	FromNickname string     `gorm:"column:from_nickname;type:character varying(36);not null;comment:回复用户昵称" json:"from_nickname"` // 回复用户昵称
	FromAvatar   string     `gorm:"column:from_avatar;type:character varying(255);not null;comment:回复头像" json:"from_avatar"`      // 回复头像
	ToUserID     int64      `gorm:"column:to_user_id;type:bigint;not null;comment:被回复用户id" json:"to_user_id"`                     // 被回复用户id
	ToNickname   string     `gorm:"column:to_nickname;type:character varying(36);not null;comment:被回复用户昵称" json:"to_nickname"`    // 被回复用户昵称
	ToAvatar     string     `gorm:"column:to_avatar;type:character varying(255);not null;comment:被回复头像" json:"to_avatar"`         // 被回复头像
	Status       int16      `gorm:"column:status;type:smallint;not null;comment:状态" json:"status"`                                // 状态
	CreateTime   time.Time  `gorm:"column:create_time;type:timestamp without time zone;not null;comment:回复时间" json:"create_time"` // 回复时间
	UpdateTime   *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"`                       // 修改时间
}

// TableName Reply's table name
func (*Reply) TableName() string {
	return TableNameReply
}
