// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTag = "tag"

// Tag mapped from table <tag>
type Tag struct {
	ID                int32   `gorm:"column:id;type:integer;not null;comment:标签信息id" json:"id"`                                                   // 标签信息id
	Title             string  `gorm:"column:title;type:character varying(100);not null;comment:标签的标题" json:"title"`                               // 标签的标题
	MediaCount        int32   `gorm:"column:media_count;type:integer;not null;comment:与标签相关联的媒体文件数量" json:"media_count"`                          // 与标签相关联的媒体文件数量
	ListingsThumbnail *string `gorm:"column:listings_thumbnail;type:character varying(400);comment:标签列表的缩略图的文件路径或 URL" json:"listings_thumbnail"` // 标签列表的缩略图的文件路径或 URL
	UserID            *int32  `gorm:"column:user_id;type:integer;comment:用户id" json:"user_id"`                                                    // 用户id
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
