// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameThumb = "thumb"

// Thumb mapped from table <thumb>
type Thumb struct {
	ID         *int64     `gorm:"column:id;type:bigint;comment:主键id" json:"id"`                                           // 主键id
	UserID     *int64     `gorm:"column:user_id;type:bigint;comment:用户id" json:"user_id"`                                 // 用户id
	CommentID  *int64     `gorm:"column:comment_id;type:bigint;comment:评论id" json:"comment_id"`                           // 评论id
	VideoID    *int64     `gorm:"column:video_id;type:bigint;comment:视频id" json:"video_id"`                               // 视频id
	CreateTime *time.Time `gorm:"column:create_time;type:timestamp(0) without time zone;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"`                 // 更新时间
}

// TableName Thumb's table name
func (*Thumb) TableName() string {
	return TableNameThumb
}
