// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID          int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:用户信息id" json:"id"`                 // 用户信息id
	Password    string     `gorm:"column:password;type:character varying(36);not null;comment:密码" json:"password"`               // 密码
	LastLogin   *time.Time `gorm:"column:last_login;type:timestamp(6) with time zone;comment:最后一次登录" json:"last_login"`          // 最后一次登录
	Username    string     `gorm:"column:username;type:character varying(36);not null;comment:用户名" json:"username"`              // 用户名
	Email       string     `gorm:"column:email;type:character varying(100);not null;comment:邮箱地址" json:"email"`                  // 邮箱地址
	Description string     `gorm:"column:description;type:text;not null;comment:用户的描述" json:"description"`                       // 用户的描述
	Nickname    string     `gorm:"column:nickname;type:character varying(50);not null;comment:用户昵称" json:"nickname"`             // 用户昵称
	CreateTime  time.Time  `gorm:"column:create_time;type:timestamp(6) with time zone;not null;comment:创建日期" json:"create_time"` // 创建日期
	Avatar      string     `gorm:"column:avatar;type:character varying(255);not null;comment:用户的头像" json:"avatar"`               // 用户的头像
	UpdateTime  time.Time  `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"`                       // 用户更新日期
	IsSuperUser *int16     `gorm:"column:is_super_user;type:smallint;comment:是否超级用户" json:"is_super_user"`                       // 是否超级用户
	IsManager   *int16     `gorm:"column:is_manager;type:smallint;comment:是否是管理员" json:"is_manager"`                             // 是否是管理员
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
