// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUsersBlock = "users_block"

// UsersBlock mapped from table <users_block>
type UsersBlock struct {
	UserID  int64 `gorm:"column:user_id;type:bigint;not null;comment:用户id" json:"user_id"`   // 用户id
	BlockID int64 `gorm:"column:block_id;type:bigint;not null;comment:模块id" json:"block_id"` // 模块id
	ID      int64 `gorm:"column:id;type:bigint;primaryKey;comment:主键id" json:"id"`           // 主键id
}

// TableName UsersBlock's table name
func (*UsersBlock) TableName() string {
	return TableNameUsersBlock
}
