// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"zhiqu/app"
	"zhiqu/app/category"
	"zhiqu/app/login"
	"zhiqu/app/user"
	"zhiqu/infrastructure/database/pgsql"
	"zhiqu/provider"
)

// Injectors from wire.go:

// wire.go 初始化模块
func NewApp() (*provider.BeanFactory, error) {
	ormer := pgsql.NewPgsqlOrm()
	dao := category.NewDao(ormer)
	service := category.NewService(dao)
	controller := category.NewController(service)
	fxRouter := category.NewAppRouter(controller)
	loginDao := login.NewDao()
	loginService := login.NewService(loginDao)
	loginController := login.NewController(loginService)
	loginFxRouter := login.NewAppRouter(loginController)
	userDao := user.NewDao(ormer)
	userService := user.NewService(userDao)
	userController := user.NewController(userService)
	userFxRouter := user.NewAppRouter(userController)
	appFxRouter := app.NewAppRouter(fxRouter, loginFxRouter, userFxRouter)
	beanFactory := provider.NewBeanFactory(appFxRouter)
	return beanFactory, nil
}
