// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"zhiqu/app/category"
	"zhiqu/app/login"
	"zhiqu/provider"
)

// Injectors from wire.go:

// wire.go 初始化模块
func NewApp() (*provider.BeanFactory, error) {
	dao := login.NewDao()
	service := login.NewService(dao)
	controller := login.NewController(service)
	categoryDao := category.NewDao()
	categoryService := category.NewService(categoryDao)
	categoryController := category.NewController(categoryService)
	beanFactory := provider.NewBeanFactory(controller, categoryController)
	return beanFactory, nil
}
